### ISSUE TITLE
No Fonts installed on this device

### ISSUE THREAD

**Issue by jamesgurung** [ststeiger/PdfSharpCore#125] opened 2020-11-01 18:23 UTC
Everything was running fine on 1.2.6, but since updating to 1.2.8 the default font resolver can no longer find fonts when deployed to a Linux container. It runs fine on Windows, but not when deployed using the following Dockerfile. The error is "No Fonts installed on this device".

```
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Install System.Drawing native dependencies
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
       libc6-dev \
       libgdiplus \
       libx11-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Microsoft core fonts
RUN echo "deb http://deb.debian.org/debian stable main contrib non-free" > /etc/apt/sources.list \
    && echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections \
    && apt-get update \
    && apt-get install -y \
        ttf-mscorefonts-installer \
    && apt-get clean \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY MyProject.csproj MyProject/
RUN dotnet restore "MyProject/MyProject.csproj"
COPY . MyProject/
WORKDIR "/src/MyProject"
RUN dotnet build "MyProject.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MyProject.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MyProject.dll"]
```

I realise it's possible to implement a custom `IFontResolver` (although I know literally nothing about where Linux fonts are installed, so wouldn't know where to start!)

Is this something that could be fixed to work by default in this scenario?

**Comment by Marv51** [comment] 2020-11-04 16:53
Yup, same here my GitHub Action Tests Fail with on Linux:
```
System.IO.FileNotFoundException: No Fonts installed on this device!
  Stack Trace:
      at PdfSharpCore.Utils.FontResolver.ResolveTypeface(String familyName, Boolean isBold, Boolean isItalic)
   at PdfSharpCore.Fonts.FontFactory.ResolveTypeface(String familyName, FontResolvingOptions fontResolvingOptions, String typefaceKey)
   at PdfSharpCore.Drawing.XGlyphTypeface.GetOrCreateFrom(String familyName, FontResolvingOptions fontResolvingOptions)
   at PdfSharpCore.Drawing.XFont.Initialize()
   at PdfSharpCore.Drawing.XFont..ctor(String familyName, Double emSize, XFontStyle style, XPdfFontOptions pdfOptions)
   at PdfSharpCore.Drawing.XFont..ctor(String familyName, Double emSize, XFontStyle style)
```

**Comment by pingvinen** [comment] 2020-11-17 11:06
I am seeing the same issue on my linux desktop machine.

**Comment by eltonina** [comment] 2020-12-22 01:29
I created this PR #132, for my work fine; I used 'ubuntu-latest' in Azure-devops

**Comment by darzid** [comment] 2021-03-02 18:46
I've tried v1.2.11 and v1.2.12 on Cent OS, but I still get the same message: "No Fonts installed on this device!".

I've also tried to copy a .ttf file to ~/.fonts, but then I still get the same message. 

Which I find strange, because the issue reported was caused by subfolders not being included. 
So, copying a single .ttf file directly to ~/.fonts (which is specified in my /etc/fonts/fonts.conf file) should not even be affected by the reported issue. Any advice?

**Comment by ststeiger** [comment] 2021-03-03 11:52
Your /etc/fonts/fonts.conf is not being read. 
The font directories are hard-coded.

**Comment by darzid** [comment] 2021-03-04 19:39
Ok. In which folders does it look then?

**Comment by mishun** [comment] 2021-03-05 02:26
If I understand correctly, it kinda reads fonts.conf, but in a very hacky way:
https://github.com/ststeiger/PdfSharpCore/blob/0f457191cf9c447a4551a19d9723c2ee5d8ea7e8/PdfSharpCore/Utils/FontResolver.cs#L60-L91

**Comment by ststeiger** [comment] 2021-03-05 11:04
Correction: It used to be hard-coded. 

Yea, unfortunately, it's hard to find a good documentation for what to do with the contents of fonts.conf. 
It looks like it searches for all directories listed directly in fonts.conf between dir-tags, then enumerates all fonts in these directories that end with ".ttf" (case-sensitive). 
Also, it only searches the top directory: 
`return InternalEnumerateFiles(path, "*", SearchOption.TopDirectoryOnly);`

**Comment by ststeiger** [comment] 2021-03-05 11:39
Fixed the top-directory issue, and replaced the .ttf regex with EndsWith (case-insensitive). 
So if your fonts.conf contains 
```
	<dir>/usr/share/fonts</dir>
	<dir>/usr/local/share/fonts</dir>
	<dir prefix="xdg">fonts</dir>
	<!-- the following element will be removed in the future -->
	<dir>~/.fonts</dir>
```
it should now find *.ttf fonts in ~/.fonts and all of its subdirectories.

**Comment by ststeiger** [comment] 2021-03-05 11:43
Question is, should we only load *.ttf, or also *.woff and *.otf.

**Comment by darzid** [comment] 2021-03-05 12:32
I only need ttf

Mvg, Steven

________________________________

**Comment by ststeiger** [comment] 2021-03-05 13:35
@darzid: 
In addition to reading the fonts.conf directory, I've now added 
```
/usr/share/fonts
/usr/local/share/fonts
System.Environment.GetEnvironmentVariable("HOME") + "/.fonts"
```
hard-coded, just in case there is no fonts.conf, or that there are no such entries. 
The fonts ending in .ttf in those folders (and subfolders) should now be picked up.

**Comment by ststeiger** [comment] 2021-03-05 13:56
@jamesgurung: Linux uses fontfonfig to configure the location of the fonts. 
Hard-coded, it now searches in /usr/share/fonts, /usr/local/share/fonts and ~/.fonts.
If you don't know where the fonts are located, you can always embed the fonts you need as embedded-resources in an assembly, and implement your own IFontResolver, which loades them from the embedded-resources in that assembly. Of course that requires that the font's license allows "embedding".

**Comment by jamesgurung** [comment] 2021-03-05 16:48
@ststeiger Many thanks. I no longer have an issue; it was a regression in 1.2.8 that I assume was fixed in a subsequent update because everything is working fine now. 👍

I haven't closed because it looks like others are having related issues.

**Comment by notclive** [comment] 2021-03-05 19:51
I found that hard-coded directories weren't working for me, fonts inside `/usr/share/fonts` weren't being picked up.
Looking at `AddFontsToFontList` it appears that fonts need to be at least two directories deep, putting a font inside `/usr/share/fonts/a/b` worked.

**Comment by darzid** [comment] 2021-03-11 15:57
Thanks!
________________________________

**Comment by ststeiger** [comment] 2021-03-12 14:32
@jamesgurung @notclive: Merged pinvoke of libfontconfig with [pull request 151](https://github.com/ststeiger/PdfSharpCore/pull/151) for Linux. 
Fonts should be resolved fine now. 
You might want to check if it works for you.

**Comment by bcourtneyri** [comment] 2021-03-24 11:52
@notclive did you have to stay with the two directory deep solution?

**Comment by ststeiger** [comment] 2021-03-26 22:56
@bcourtneyri: Does the container have truetype-fonts installed ?

**Comment by bcourtneyri** [comment] 2021-03-27 11:42
@ststeiger thanks for the follow up. The container itself does not. I'm considering whether to mount a volume with .ttfs to the linux server or to package the .ttf fonts within the asp net core project. Is it possible to do some sort of font resolve with packaged .ttfs?

**Comment by ststeiger** [comment] 2021-03-27 21:32
Sure, you can make a dll where the ttfs are an embedded resource. 
Then you need to implement a font-resolver that reads fonts from the embedded resources.

**Comment by bcourtneyri** [comment] 2021-03-29 14:15
@ststeiger thanks again. I managed to it working using the sample code you provided.

**Comment by Hummel37** [comment] 2021-06-21 19:27
Relates to https://github.com/ststeiger/PdfSharpCore/issues/161

**Closed** 2021-12-30 15:56 UTC

**Comment by diogoxluis** [comment] 2023-12-06 18:45
I'm getting "No Fonts installed on this device!" error, running version 1.3.62 on .net7.0 linux container.

Do I need to do any extra step or should it just work?



System.IO.FileNotFoundException: No Fonts installed on this device!
   at PdfSharpCore.Utils.FontResolver.ResolveTypeface(String familyName, Boolean isBold, Boolean isItalic)
   at PdfSharpCore.Fonts.FontFactory.ResolveTypeface(String familyName, FontResolvingOptions fontResolvingOptions, String typefaceKey)
   at PdfSharpCore.Drawing.XGlyphTypeface.GetOrCreateFrom(String familyName, FontResolvingOptions fontResolvingOptions)
   at PdfSharpCore.Drawing.XFont.Initialize()
   at PdfSharpCore.Drawing.XFont..ctor(String familyName, Double emSize, XFontStyle style, XPdfFontOptions pdfOptions)
   at PdfSharpCore.Drawing.XFont..ctor(String familyName, Double emSize)
   at PdfSharpCore.Pdf.AcroForms.PdfTextField..ctor(PdfDictionary dict)
   at PdfSharpCore.Pdf.AcroForms.PdfAcroField.PdfAcroFieldCollection.CreateAcroField(PdfDictionary dict)
   at PdfSharpCore.Pdf.AcroForms.PdfAcroField.PdfAcroFieldCollection.get_Item(Int32 index)
   at PdfSharpCore.Pdf.PdfDocument.MakeAcroFormsReadOnly()
   at DSServer.Commands.ConvertToPDF.ConvertToPDF.ExecuteAsync(MemoryStream originalFile) in /app/src/DSServer/Commands/ConvertToPDF/ConvertToPDF.cs:line 30
   at REG.Documents.Business.DocumentExchangeItemMessageAttachments.Commands.Download.DownloadDocumentExchangeItemMessageAttachmentCommand.ExecutePdfForRecipientAsync(Guid attachmentId, Stream target) in /app/src/REG.Documents.Business/DocumentExchangeItemMessageAttachments/Commands/Download/DownloadDocumentExchangeItemMessageAttachmentCommand.cs:line 172
   at REG.Documents.Api.Controllers.DocumentExchangeItemMessageAttachmentController.DownloadMessageAttachmentForRecipient(Guid attachmentId) in /app/src/REG.Documents.Api/Controllers/DocumentExchangeItemMessageAttachmentController.cs:line 102
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by diogoxluis** [comment] 2023-12-07 09:25
> @diogoxluis I packaged the fonts into my app and referenced them from there. It worked for me as I only needed a few.

Thanks... any pointers to how I do that?
I tried the dockerfile code at the top, but didn't do the trick for me.

**Comment by bcourtneyri** [comment] 2023-12-07 10:50
You just put the ttf files into a folder somewhere in your project and refer to them in the code.

**Comment by Rahul-Vaity** [comment] 2024-04-03 09:59
After using 1.2.6 version I'm getting "The type initializer for 'PdfSharpCore.Utils.FontResolver' threw an exception".
